### ISSUE TITLE
Undefined in Standard output log

### ISSUE THREAD

**Issue by smoliji** [AckeeCZ/cosmas#4]
Standard output log at the end of the request contains 'undefined' in the message string.

> 200 POST /path/to/endpoint 89.777 ms undefined - Standard output

I cannot find the log structure in the docs, but i think this part of the message should be skipped

> 200 POST /path/to/endpoint 89.777 ms - Standard output
👍

**Comment by smoliji** [comment]
The same goes for the Request accepted

> --- POST /api/v1/manipulator-events/vehicle-states undefined - Request accepted

**Comment by vlasy** [comment]
Will be fixed in next release
